config/routes.rb
Rails.application.routes.draw do
  get 'users/wishlist', to: 'users#wishlist'
  resources :rentals, except: %i[new edit]
  resources :offers do
    resources :reviews, only: [ :new, :create ]
  end
  devise_for :users
  get 'dashboard', to: 'pages#dashboard'
  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user # le vendeur
  has_many :rentals
  has_many :users, through: :rentals
  has_many :reviews, dependent: :destroy
  has_many_attached :photos
  validates :name, presence: true
  validates :price, presence: true
  # has_one_attached :photo
  validates :description, presence: true
  validates :address, presence: true
  validates :photos, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  include PgSearch::Model
  pg_search_scope :search_by_name_and_description,
    against: [ :name, :description, :address ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user # le client
  belongs_to :offer
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :total_amount, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :offer
  validates :content, presence: true, length: { minimum: 5 }
  validates :rating, presence: true, inclusion: 1..5
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :rentals
  has_many :offers
  has_one_attached :photo
  validates :username, presence: true
  # validates :email, presence: true
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :phone_number, presence: true
  validates :photo, presence: true
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :user
  belongs_to :offer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :phone_number, :photo, :username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :email, :phone_number, :photo, :username])
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: :index
  skip_before_action :authenticate_user!, only: :show

  def index
    if params[:query].present?
      @offers = policy_scope(Offer.search_by_name_and_description(params[:query]))
    else
      @offers = policy_scope(Offer).order(created_at: :desc)
    end

    @markers = @offers.geocoded.map do |offer|
      {
        lat: offer.latitude,
        lng: offer.longitude,
        info_window: render_to_string(partial: "info_window", locals: { offer: offer })
      }
    end
  end

  def show
    authorize @offer
    @rental = Rental.new
    @rental.offer = @offer
  end

  def new
    @offer = Offer.new
    authorize @offer
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.user = current_user
    authorize @offer
    if @offer.save
      @offer.price = @offer.price.round(2)
      redirect_to offer_path(@offer), notice: 'Offer was successfully created.'
    else
      render :new
    end
  end

  def edit
    authorize @offer
  end

  def update
    authorize @offer
    @offer.update(offer_params)
    redirect_to offer_path(@offer)
  end

  def destroy
    authorize @offer
    @offer.rentals.each(&:destroy)
    @offer.destroy
    redirect_to offers_path
  end

  private

  def set_offer
    @offer = Offer.find(params[:id])
  end

  def offer_params
    params.require(:offer).permit(:name, :price, :description, :avaibility, :address, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
    @offers = Offer.all
  end

  def dashboard

  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  def index
    @rentals = policy_scope(Rental).where(user: current_user)
  end

  def show
    @rental = Rental.find(params[:id])
    authorize @rental
  end

  def create
    @rental = Rental.new(rental_params)
    authorize @rental
    @rental.user = current_user
    @rental.offer = Offer.find(params[:offer_id])
    nb_days = (@rental.end_time - @rental.start_time).to_i + 1
    @rental.total_amount = (nb_days * @rental.offer.price).round(2)
    if @rental.save!
      redirect_to rentals_path
    else
      render :new
    end
  end

  def edit
    @rental = Rental.find(params[:id])
    authorize @rental
  end

  def update
    @rental = Rental.find(params[:id])
    authorize @rental
    @rental.update(rental_params)
    nb_days = (@rental.end_time - @rental.start_time).to_i + 1
    @rental.update(total_amount: (nb_days * @rental.offer.price).round(2))
    redirect_to rentals_path
  end

  def destroy
    @rental = Rental.find(params[:id])
    authorize @rental
    @rental.destroy
    redirect_to rentals_path
  end

  private

  def rental_params
    params.require(:rental).permit(:user_id, :offer_id, :start_time, :end_time, :total_amount)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  skip_after_action :verify_authorized
  skip_after_action :verify_policy_scoped

  def new
    @offer = Offer.find(params[:offer_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @rental = Rental.new
    @offer = Offer.find(params[:offer_id])
    @review.offer = @offer
    if @review.save
      redirect_to offer_path(@offer)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: :show

  def show
    @user = current_user
  end

  def wishlist
  end

  private

  def user_params
    params.require(:user).permit(:email, :last_name, :first_name, :phone_number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roflex</title>
    <link rel="icon" href= <%= image_url('roflex-favicon.png') %> />
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="wrapper">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/offers/_info_window.html.erb
<div class="window">
  <%= link_to offer, class:"card-offer" do %>
  <%= cl_image_tag offer.photos.first.key %>
  <h5 class="mt-2"><%= offer.name %></h5>
  <h6>💵 <strong><%= offer.price %>€ /day</strong></h6>
  <p>📍 <%= offer.address %></p>
  <% end %>
</div>

app/views/offers/create.html.erb
<h1>Offers#create</h1>
<p>Find me in app/views/offers/create.html.erb</p>

app/views/offers/destroy.html.erb
<h1>Offers#destroy</h1>
<p>Find me in app/views/offers/destroy.html.erb</p>

app/views/offers/show.html.erb
<div class="container mt-5 offershow">
  <div class="row">
    <div class="col-sm-6 mb-3">
      <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <% @offer.photos.each_with_index do |photo, i| %>
            <div class="carousel-item <%= "active" if i == 0 %>">
              <%= cl_image_tag photo.key, class:"d-block w-100 img-show" %>
            </div>
          <% end %>
        </div>
        <% if @offer.photos.count > 1 %>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        <% end %>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="info-container">
        <h1><%= @offer.name %></h1>
        <p><%= @offer.description %></p>
        <p class="blue"><i class="fas fa-tag"></i> <strong><span id="priceperday"><%= '%.2f' % @offer.price %></span>€</strong>/day</p>
      </div>
      <% if @offer.user == current_user %>
        <div class="mb-3">
          <%= link_to("Edit", edit_offer_path(@offer),class:"edit btn") %>
          <%= link_to("Delete", offer_path(@offer),class:"delete btn", method: :delete, data: {confirm: "Are you sure?"}) %>
        </div>
      <% else %>
        <div class="action-container mb-5" data-controller="dynamicprice">
          <%= simple_form_for @rental do |f| %>
            <%= f.input :start_time, as: :date, html5: true,label: "Start date", input_html:{value: Date.today, data:{action:"change->dynamicprice#updatePrice"}} %>
            <%= f.input :end_time, as: :date, html5: true, label: "End date", input_html:{value: Date.today, data:{action:"change->dynamicprice#updatePrice"}} %>
            <%= hidden_field_tag :offer_id, @offer.id %>
            <p class="blue"><i class="fas fa-shopping-cart"></i> <strong><span data-dynamicprice-target="price" id="realprice"><%= '%.2f' % @offer.price %> €</span></strong></p>
            <%= f.submit "Rent it", class:"btn", id:"rent-btn" %>
          <% end %>
      <% end %>
      </div>
    </div>
  </div>

  <div class="container mb-5 mt-3">
    <h2>Last reviews</h2>
      <p><%= pluralize((@offer.reviews.count),'review') %> </p>
        <% if @offer.reviews.count > 0 %>
            <div class="row mb-3">
              <% @offer.reviews.each do |review| %>
                <div class="card-review col-md-3 m-2 p-3">
                  <p class="blue"><%= "★" * review.rating %><%= "☆" * (5 - review.rating) %></p>
                  <p class="blue"><%= review.content %></p>
                </div>
              <% end %>
            </div>
            <%= link_to 'Leave a review', new_offer_review_path(@offer), class: "col-md-2 btn btn-primary" %>
        <% else %>
            <%= link_to 'Leave the first review for this product', new_offer_review_path(@offer) %>
        <% end %>
  </div>

  <div class="mt-5 mb-5 container">
  <h2 class = "mb-5">You may also like</h2>

   <div class="row">
    <% Offer.all.last(3).each do |offer| %>
        <div class="col-sm-6 col-md-4 mb-3">
          <%= link_to offer, class:"card-offer-link" do %>
            <div class="card-offer">
              <% if offer.photos.attached? %>
                <%= cl_image_tag offer.photos.first.key %>
              <% else %>
                <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
              <% end %>
              <div class="card-offer-infos">
                <div class="card-offer-infos-top">
                  <p class="card-offer-name"><%= offer.name %></p>
                  <p class="card-offer-description"><%= offer.description.truncate(110) %></p>
                </div>
                <div class="card-offer-infos-bottom">
                  <p class="card-offer-pricing"><%= '%.2f' % offer.price %>€/day</p>
                  <p class="card-offer-address">📍 <%= offer.address %></p>
                </div>
                <% if offer.user.photo.attached? %>
                  <%= cl_image_tag offer.user.photo.key, class:"card-offer-user avatar-bordered" %>
                <% else %>
                  <img src="https://media.istockphoto.com/vectors/default-profile-picture-avatar-photo-placeholder-vector-illustration-vector-id1223671392?k=20&m=1223671392&s=612x612&w=0&h=lGpj2vWAI3WUT1JeJWm1PRoHT3V15_1pdcTn2szdwQ0=" class="card-offer-user avatar-bordered" />
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
  </div>

</div>
</div>

app/views/offers/update.html.erb
<h1>Offers#update</h1>
<p>Find me in app/views/offers/update.html.erb</p>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), url(https://res.cloudinary.com/dq5va7hrp/image/upload/v1645795026/photo-1548359638-e51353ca6d34_cqs1gj.jpg);">
  <div class="container home">
    <h1>Rent beautiful watches</h1>
    <p>The luxury you've always deserved.</p>
    <div class= "search-home"><%= render 'shared/searchbar' %></div>
  </div>
</div>

<div class="mt-5 container">
  <h2 class = "mb-5">Roflex selection for today</h2>

   <div class="row">
    <% @offers.first(3).each do |offer| %>
        <div class="col-sm-6 col-md-4 mb-3">
          <%= link_to offer, class:"card-offer-link" do %>
            <div class="card-offer">
              <% if offer.photos.attached? %>
                <%= cl_image_tag offer.photos.first.key %>
              <% else %>
                <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
              <% end %>
              <div class="card-offer-infos">
                <div class="card-offer-infos-top">
                  <p class="card-offer-name"><%= offer.name %></p>
                  <p class="card-offer-description"><%= offer.description.truncate(110) %></p>
                </div>
                <div class="card-offer-infos-bottom">
                  <p class="card-offer-pricing"><%= '%.2f' % offer.price %>€/day</p>
                  <p class="card-offer-address">📍 <%= offer.address %></p>
                </div>
                <% if offer.user.photo.attached? %>
                  <%= cl_image_tag offer.user.photo.key, class:"card-offer-user avatar-bordered" %>
                <% else %>
                  <img src="https://media.istockphoto.com/vectors/default-profile-picture-avatar-photo-placeholder-vector-illustration-vector-id1223671392?k=20&m=1223671392&s=612x612&w=0&h=lGpj2vWAI3WUT1JeJWm1PRoHT3V15_1pdcTn2szdwQ0=" class="card-offer-user avatar-bordered" />
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
  </div>
  <div class="text-center">
    <%= link_to("See more", offers_path, class:"btn") %>
  </div>

</div>

<div class="banner-child mt-5" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1495704907664-81f74a7efd9b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80);">
  <div class="container">
    <h2>Your rolex is sleeping in a drawer ?</h2>
    <p>You can make money out of it.</p>
      <%= link_to("Rent it out", new_offer_path, class:"btn") %>
    </div>
  </div>
</div>

<div class="container mt-5 mb-5">
  <h2 class = "mb-5">Our last news</h2>
  <div class="row">
    <div class="col-md-6">
        <div class="card-category mb-3" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1594534475808-b18fc33b045e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80)">
          New rolex Submariner
        </div>
    </div>
    <div class="col-md-6">
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1625328923319-74cafe485866?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80)">
          New store in Dubai
        </div>
    </div>
  </div>
</div>

app/views/rentals/index.html.erb
<div class="container my-4">
  <h1 class="mb-3">My rentals</h1>
  <nav>
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
      <button class="nav-link active" id="nav-rentals-tab" data-bs-toggle="tab" data-bs-target="#nav-rentals" type="button" role="tab" aria-controls="nav-rentals" aria-selected="true">My rentals (as renter)</button>
      <button class="nav-link" id="nav-contact-tab" data-bs-toggle="tab" data-bs-target="#nav-contact" type="button" role="tab" aria-controls="nav-contact" aria-selected="false">My rentals (as owner)</button>
      <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">My offers (as owner)</button>
    </div>
  </nav>
  <div class="tab-content mt-3" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-rentals" role="tabpanel" aria-labelledby="nav-rentals-tab">
      <div class="row">
        <% if current_user.rentals.count == 0 %>
          <div class="container">
            <p class="mt-3">You haven't rent any watch yet but it's never too late !</p>
            <%= link_to("Discover products", offers_path, class:"btn") %>
          </div>
        <% end %>
        <% current_user.rentals.reverse.each do |rental| %>
          <div class="col-sm-6 col-md-4 mb-3">
            <%= link_to rental, class:"card-offer-link" do %>
              <div class="card-offer">
                <% if rental.offer.photos.attached? %>
                  <%= cl_image_tag rental.offer.photos.first.key %>
                <% else %>
                  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
                <% end %>
                <div class="card-offer-infos">
                  <div class="card-offer-infos-top">
                    <p class="card-offer-name"><%= rental.offer.name %></p>
                    <p class="card-offer-description"><%= rental.offer.description.truncate(110) %></p>
                  </div>
                  <div class="card-offer-infos-bottom">
                    <div class="d-flex align-items-end">
                      <p class="card-offer-pricing"><%= '%.2f' % rental.total_amount %>€</p>
                      <% if rental.start_time > Date.today %>
                        <p class="tag future">To come</p>
                      <% elsif rental.end_time < Date.today %>
                        <p class="tag past">Over</p>
                      <% else %>
                        <p class="tag present">Ongoing</p>
                      <% end %>
                    </div>
                    <p class="card-offer-address">📍 <%= rental.offer.address %></p>
                  </div>
                  <% if rental.offer.user.photo.attached? %>
                    <%= cl_image_tag rental.offer.user.photo.key, class:"card-offer-user avatar-bordered" %>
                  <% else %>
                    <img src="https://media.istockphoto.com/vectors/default-profile-picture-avatar-photo-placeholder-vector-illustration-vector-id1223671392?k=20&m=1223671392&s=612x612&w=0&h=lGpj2vWAI3WUT1JeJWm1PRoHT3V15_1pdcTn2szdwQ0=" class="card-offer-user avatar-bordered" />
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
      <div class="row">
        <% if current_user.offers.count == 0 %>
          <div class="container">
            <p class="mt-3">It seems like you haven't posted any offer yet !</p>
            <%= link_to("Add a new offer", new_offer_path, class:"btn") %>
          </div>
        <% elsif @rentals.select { |rental| rental.offer.user == current_user }.count == 0 %>
          <div class="container">
            <p class="mt-3">Nobody has rent one of your watches, yet!</p>
            <%= link_to("Add a new offer", new_offer_path, class:"btn") %>
          </div>
        <% end %>
        <% @rentals.select { |rental| rental.offer.user == current_user }.reverse.each do |rental| %>
          <div class="col-sm-6 col-md-4 mb-3">
            <%= link_to rental, class:"card-offer-link" do %>
              <div class="card-offer">
                <% if rental.offer.photos.attached? %>
                  <%= cl_image_tag rental.offer.photos.first.key %>
                <% else %>
                  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
                <% end %>
                <div class="card-offer-infos">
                  <div class="card-offer-infos-top">
                    <p class="card-offer-name"><%= rental.offer.name %></p>
                    <p class="card-offer-description"><%= rental.offer.description.truncate(110) %></p>
                  </div>
                  <div class="card-offer-infos-bottom">
                    <div class="d-flex align-items-end">
                      <p class="card-offer-pricing"><%= '%.2f' % rental.total_amount %>€</p>
                      <% if rental.start_time > Date.today %>
                        <p class="tag future">To come</p>
                      <% elsif rental.end_time < Date.today %>
                        <p class="tag past">Over</p>
                      <% else %>
                        <p class="tag present">Ongoing</p>
                      <% end %>
                    </div>
                    <p class="card-offer-address">📍 <%= rental.offer.address %></p>
                  </div>
                  <% if rental.offer.user.photo.attached? %>
                    <%= cl_image_tag rental.offer.user.photo.key, class:"card-offer-user avatar-bordered" %>
                  <% else %>
                    <img src="https://media.istockphoto.com/vectors/default-profile-picture-avatar-photo-placeholder-vector-illustration-vector-id1223671392?k=20&m=1223671392&s=612x612&w=0&h=lGpj2vWAI3WUT1JeJWm1PRoHT3V15_1pdcTn2szdwQ0=" class="card-offer-user avatar-bordered" />
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
      <div class="row">
        <% if current_user.offers.count == 0 %>
          <div class="container">
            <p class="mt-3">It seems like you haven't posted any offer yet !</p>
            <%= link_to("Add a new offer", new_offer_path, class:"btn") %>
          </div>
        <% end %>
        <% current_user.offers.reverse.each do |offer| %>
          <div class="col-sm-6 col-md-4 mb-3">
            <%= link_to offer, class:"card-offer-link" do %>
              <div class="card-offer">
                <% if offer.photos.attached? %>
                  <%= cl_image_tag offer.photos.first.key %>
                <% else %>
                  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
                <% end %>
                <div class="card-offer-infos">
                  <div class="card-offer-infos-top">
                    <p class="card-offer-name"><%= offer.name %></p>
                    <p class="card-offer-description"><%= offer.description.truncate(110) %></p>
                  </div>
                  <div class="card-offer-infos-bottom">
                    <p class="card-offer-pricing"><%= '%.2f' % offer.price %>€/day</p>
                    <p class="card-offer-address">📍 <%= offer.address %></p>
                  </div>
                  <% if offer.user.photo.attached? %>
                    <%= cl_image_tag offer.user.photo.key, class:"card-offer-user avatar-bordered" %>
                  <% else %>
                    <img src="https://media.istockphoto.com/vectors/default-profile-picture-avatar-photo-placeholder-vector-illustration-vector-id1223671392?k=20&m=1223671392&s=612x612&w=0&h=lGpj2vWAI3WUT1JeJWm1PRoHT3V15_1pdcTn2szdwQ0=" class="card-offer-user avatar-bordered" />
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<%# <% <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
   <i class="fas fa-gem"></i> Roflex Ltd.
  </div>
</div> %>
<div class = "footer">
    <div class="container py-3">
      <div class="row py-4">

          <div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
            <h6 class="text-uppercase font-weight-bold mb-4">Shop</h6>
            <ul class="list-unstyled mb-0">
              <li class="mb-2"><%= link_to("Products", offers_path) %></li>
              <li class="mb-2"><%= link_to("My rentals", rentals_path) %></li>
              <li class="mb-2"><%= link_to("Add an offer", new_offer_path) %></li>
            </ul>
          </div>

          <div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
            <h6 class="text-uppercase font-weight-bold mb-4 ">Company</h6>
            <ul class="list-unstyled mb-0">
              <li class="mb-2"><%= link_to("Sign in", new_user_session_path) %></li>
              <li class="mb-2"><%= link_to("Sign up", new_user_registration_path) %></li>
              <li class="mb-2"><a href="#" class="">Our Blog</a></li>
            </ul>
          </div>

          <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
            <p class="font-italic ">Flex with your rolex <i class="fas fa-gem"></i></p>
          </div>

          <div class="col-lg-4 col-md-6 mb-lg-0">
            <h6 class="text-uppercase font-weight-bold mb-4 border-bottom border-light ">Newsletter</h6>
            <p class="mb-4 ">Follow our news to be aware of our new offers to keep flexing</p>
            <div class="p-1 rounded border mb-4">
              <div class="input-group">
                <input type="email" placeholder="Enter your email address" aria-describedby="button-addon1" class="form-control border-0 shadow-0">
                <div class="input-group-append">
                  <button id="button-addon1" type="submit" class="btn btn-link"><i class="fa fa-paper-plane"></i></button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
</div>